### ISSUE TITLE
CUI minimum requirement + SDK docs

### ISSUE THREAD

**Issue by marc2k3** [reupen/yuo.be#1]
CUI v1.3 requires fb2k v1.4 or above whereas the download page states it will work on fb2k v1.3. Perhaps you missed the fb2k SDK default changing here?

https://github.com/reupen/foobar2000-sdk-modified/commit/c4abf0c3e224d50dda66774652c6991187a80f8d#diff-d2ebc2e5a26222fc4a2da53ef750b367

Also, this link on SDK page is dead.

https://yuo.be/columns_ui-sdk-documentation/

**Comment by reupen** [comment]
Thanks, I've corrected the minimum foobar2000 version on the website.

The SDK docs were a bit out-of-date too – I'll make an effort to update them and then resurrect them.

**Comment by reupen** [comment]
The docs are now at https://columns-ui-sdk.readthedocs.io and have had a slight refresh and update 🙂 

The old URL redirects there.

Thanks!

**Comment by marc2k3** [comment]
Nice. 👍
